/**
 * @file themePalette.ts
 * @project Spine Viewer Pro
 * @author Andrii Karpus <andryuha.ka@gmail.com>
 * @copyright 2026 Andrii Karpus
 * @built-with Claude Code (https://claude.ai/claude-code)
 */

import type { GlobalThemeOverrides } from 'naive-ui'

export type ThemeName = 'dark' | 'light'

export const PALETTES = [
  { id: 'mono',     label: 'Studio Mono' },
  { id: 'darkroom', label: 'Darkroom Neutral' },
  { id: 'slate',    label: 'Slate Scrub' },
  { id: 'rose',     label: 'Keyframe Rose' },
  { id: 'graphite', label: 'Graphite Teal' },
] as const

export type PaletteName = typeof PALETTES[number]['id']

export function isPalette(v: unknown): v is PaletteName {
  return PALETTES.some(p => p.id === v)
}

// must match the --c-* tokens in src/assets/themes.css (checked by tests/utils/themePalette.test.ts)
export const PALETTE = {
  mono: {
    dark: {
      bg:           '#000000',
      surface:      '#0c0c0c',
      raised:       '#181818',
      border:       '#2e2e2e',
      borderStrong: '#7a7a7a',
      text:         '#fafafa',
      textDim:      '#d4d4d4',
      textMuted:    '#b0b0b0',
      textGhost:    '#8c8c8c',
      accent:       '#f5f7fa',
      accentHover:  '#ffffff',
      accentText:   '#0a0a0a',
      hover:        '#1f1f1f',
      selection:    '#2a2a2a',
      success:      '#4ade80',
      warning:      '#fbbf24',
      error:        '#ff6b6b',
      info:         '#7cb4ff',
    },
    light: {
      bg:           '#f4f4f4',
      surface:      '#ffffff',
      raised:       '#e8e8e8',
      border:       '#cfcfcf',
      borderStrong: '#6b6b6b',
      text:         '#000000',
      textDim:      '#262626',
      textMuted:    '#4a4a4a',
      textGhost:    '#636363',
      accent:       '#0a0a0a',
      accentHover:  '#333333',
      accentText:   '#ffffff',
      hover:        '#ebebeb',
      selection:    '#e0e0e0',
      success:      '#146c2e',
      warning:      '#8a5100',
      error:        '#b3261e',
      info:         '#0369a1',
    },
  },
  darkroom: {
    dark: {
      bg:           '#111111',
      surface:      '#181818',
      raised:       '#222222',
      border:       '#2c2c2c',
      borderStrong: '#6e6e6e',
      text:         '#e8e8e8',
      textDim:      '#c6c6c6',
      textMuted:    '#a3a3a3',
      textGhost:    '#8f8f8f',
      accent:       '#4d9fff',
      accentHover:  '#75b5ff',
      accentText:   '#08182c',
      hover:        '#252525',
      selection:    '#1b2b40',
      success:      '#5ccf7e',
      warning:      '#f0b429',
      error:        '#ff6b6b',
      info:         '#3dc9d6',
    },
    light: {
      bg:           '#f0f0f0',
      surface:      '#fafafa',
      raised:       '#e4e4e4',
      border:       '#d6d6d6',
      borderStrong: '#818181',
      text:         '#1b1b1b',
      textDim:      '#393939',
      textMuted:    '#575757',
      textGhost:    '#606060',
      accent:       '#185bbf',
      accentHover:  '#1552ad',
      accentText:   '#ffffff',
      hover:        '#e8e8e8',
      selection:    '#dbe7f9',
      success:      '#1c7438',
      warning:      '#945700',
      error:        '#b83729',
      info:         '#0b707b',
    },
  },
  slate: {
    dark: {
      bg:           '#0e1116',
      surface:      '#151a21',
      raised:       '#1c222b',
      border:       '#2a323d',
      borderStrong: '#6b7888',
      text:         '#e6eaf0',
      textDim:      '#c0c8d2',
      textMuted:    '#9aa5b4',
      textGhost:    '#85909e',
      accent:       '#22c3d6',
      accentHover:  '#4fd6e6',
      accentText:   '#04232a',
      hover:        '#212731',
      selection:    '#123640',
      success:      '#4ade80',
      warning:      '#fbbf24',
      error:        '#f87171',
      info:         '#7aa7ff',
    },
    light: {
      bg:           '#f3f5f8',
      surface:      '#ffffff',
      raised:       '#e9edf2',
      border:       '#d3d9e1',
      borderStrong: '#7c8899',
      text:         '#141a22',
      textDim:      '#333c48',
      textMuted:    '#525e6e',
      textGhost:    '#5b6676',
      accent:       '#0a6e80',
      accentHover:  '#086a78',
      accentText:   '#ffffff',
      hover:        '#edf1f5',
      selection:    '#d5eef2',
      success:      '#147a3a',
      warning:      '#9e5a07',
      error:        '#c62828',
      info:         '#1d5fd1',
    },
  },
  rose: {
    dark: {
      bg:           '#111316',
      surface:      '#181b1f',
      raised:       '#21252b',
      border:       '#2c3139',
      borderStrong: '#6f7782',
      text:         '#ebedf0',
      textDim:      '#c6cad2',
      textMuted:    '#a1a8b3',
      textGhost:    '#8b929c',
      accent:       '#f269a8',
      accentHover:  '#f57db4',
      accentText:   '#2a0717',
      hover:        '#252930',
      selection:    '#3a1b2b',
      success:      '#4fd18b',
      warning:      '#f5b83d',
      error:        '#ff7d5c',
      info:         '#6aa8ff',
    },
    light: {
      bg:           '#f5f5f6',
      surface:      '#ffffff',
      raised:       '#eceef1',
      border:       '#d8dbe0',
      borderStrong: '#818893',
      text:         '#17191c',
      textDim:      '#363a40',
      textMuted:    '#555b64',
      textGhost:    '#616770',
      accent:       '#c0185a',
      accentHover:  '#a3144c',
      accentText:   '#ffffff',
      hover:        '#f0f1f4',
      selection:    '#fbe3ee',
      success:      '#1a7b43',
      warning:      '#975800',
      error:        '#bf401e',
      info:         '#1f5fbf',
    },
  },
  graphite: {
    dark: {
      bg:           '#151311',
      surface:      '#1c1917',
      raised:       '#262321',
      border:       '#37322e',
      borderStrong: '#7d746c',
      text:         '#eeeae6',
      textDim:      '#ccc6c0',
      textMuted:    '#aaa29a',
      textGhost:    '#978f88',
      accent:       '#2cc9b5',
      accentHover:  '#5ad8c8',
      accentText:   '#04201c',
      hover:        '#2c2825',
      selection:    '#163631',
      success:      '#6fd37f',
      warning:      '#f0b44a',
      error:        '#ff7a6b',
      info:         '#86aaff',
    },
    light: {
      bg:           '#f5f3f0',
      surface:      '#fffdfb',
      raised:       '#ebe7e2',
      border:       '#d9d3cc',
      borderStrong: '#857c73',
      text:         '#1c1917',
      textDim:      '#3c3632',
      textMuted:    '#5b534c',
      textGhost:    '#69615b',
      accent:       '#0a6d62',
      accentHover:  '#09685d',
      accentText:   '#ffffff',
      hover:        '#efebe7',
      selection:    '#d6efea',
      success:      '#2b762e',
      warning:      '#955800',
      error:        '#bc382a',
      info:         '#1d5fd1',
    },
  },
} as const satisfies Record<PaletteName, Record<ThemeName, Record<string, string>>>

export function naiveOverrides(palette: PaletteName, mode: ThemeName): GlobalThemeOverrides {
  const p = PALETTE[palette][mode]
  return {
    common: {
      primaryColor:        p.accent,
      primaryColorHover:   p.accentHover,
      primaryColorSuppl:   p.accentHover,
      primaryColorPressed: p.textMuted,
      infoColor:           p.info,
      infoColorHover:      p.info,
      successColor:        p.success,
      successColorHover:   p.success,
      warningColor:        p.warning,
      warningColorHover:   p.warning,
      errorColor:          p.error,
      errorColorHover:     p.error,
      bodyColor:           p.bg,
      cardColor:           p.surface,
      modalColor:          p.surface,
      popoverColor:        p.surface,
      borderColor:         p.borderStrong,
      dividerColor:        p.border,
      textColorBase:       p.text,
      textColor1:          p.text,
      textColor2:          p.textDim,
      textColor3:          p.textMuted,
      hoverColor:          p.hover,
      pressedColor:        p.selection,
    },
  }
}
